export const LOAD_MOVIES_START = 'MOVIES/LOAD_START';
export const LOAD_MOVIES_SUCCESS = 'MOVIES/LOAD_SUCCESS';
export const LOAD_MOVIES_ERROR = 'MOVIES/LOAD_ERROR';

export const VOTE_MOVIE_START = 'MOVIES/VOTE_START';
export const VOTE_MOVIE_SUCCESS = 'MOVIES/VOTE_SUCCESS';
export const VOTE_MOVIE_ERROR = 'MOVIES/VOTE_ERROR';
